package restarhalf.stellar.schedule.ui.screens.foodroulette

import kotlinx.serialization.Serializable
import restarhalf.stellar.schedule.domain.model.Campus

@Serializable
data class FoodItem(
    val name: String,
    /** 点餐/店铺链接，可为空；为空时结果页仅展示菜名 */
    val qrContent: String = "",
)

// 过渡期两校区共用的通用食物列表（原占位假链接已移除）
private val commonFoodItems = listOf(
    FoodItem("火锅"),
    FoodItem("烧烤"),
    FoodItem("麻辣烫"),
    FoodItem("炸鸡"),
    FoodItem("披萨"),
    FoodItem("寿司"),
    FoodItem("拉面"),
    FoodItem("汉堡"),
    FoodItem("米线"),
    FoodItem("螺蛳粉"),
    FoodItem("烤鱼"),
    FoodItem("饺子"),
    FoodItem("包子"),
    FoodItem("煎饼果子"),
    FoodItem("肉夹馍"),
    FoodItem("黄焖鸡"),
    FoodItem("酸菜鱼"),
    FoodItem("红烧肉"),
    FoodItem("糖醋排骨"),
    FoodItem("宫保鸡丁"),
    FoodItem("鱼香肉丝"),
    FoodItem("麻婆豆腐"),
    FoodItem("回锅肉"),
    FoodItem("水煮鱼"),
    FoodItem("小龙虾"),
    FoodItem("烤串"),
    FoodItem("铁板烧"),
    FoodItem("炒饭"),
    FoodItem("炒面"),
    FoodItem("馄饨"),
    FoodItem("小笼包"),
    FoodItem("烧卖"),
    FoodItem("肠粉"),
    FoodItem("叉烧"),
    FoodItem("煲仔饭"),
    FoodItem("牛腩粉"),
    FoodItem("云吞面"),
    FoodItem("烧鹅"),
    FoodItem("白切鸡"),
    FoodItem("盐焗鸡"),
    FoodItem("梅菜扣肉"),
    FoodItem("葱油拌面"),
    FoodItem("重庆小面"),
    FoodItem("刀削面"),
    FoodItem("热干面"),
    FoodItem("肠旺面"),
    FoodItem("牛肉面"),
    FoodItem("炸酱面"),
    FoodItem("凉皮"),
    FoodItem("肉丸"),
    FoodItem("烤鸭"),
    FoodItem("糖葫芦"),
    FoodItem("臭豆腐"),
    FoodItem("煎饺"),
    FoodItem("春卷"),
    FoodItem("蛋炒饭"),
    FoodItem("麻辣香锅"),
    FoodItem("干锅"),
    FoodItem("冒菜"),
    FoodItem("钵钵鸡"),
    FoodItem("串串香"),
    FoodItem("担担面"),
    FoodItem("兔头"),
    FoodItem("夫妻肺片"),
    FoodItem("口水鸡"),
    FoodItem("樟茶鸭"),
    FoodItem("甜水面"),
    FoodItem("龙抄手"),
    FoodItem("赖汤圆"),
    FoodItem("钟水饺"),
    FoodItem("三大炮"),
    FoodItem("蛋烘糕"),
    FoodItem("军屯锅盔"),
    FoodItem("叶儿粑"),
    FoodItem("甜皮鸭"),
    FoodItem("跷脚牛肉"),
    FoodItem("豆腐脑"),
    FoodItem("油条"),
    FoodItem("豆浆"),
    FoodItem("糯米鸡"),
    FoodItem("虾饺"),
    FoodItem("凤爪"),
    FoodItem("排骨蒸饺"),
    FoodItem("马拉糕"),
    FoodItem("萝卜糕"),
    FoodItem("芋头糕"),
    FoodItem("流沙包"),
    FoodItem("奶黄包"),
    FoodItem("叉烧包"),
    FoodItem("蛋挞"),
    FoodItem("双皮奶"),
    FoodItem("姜撞奶"),
    FoodItem("杨枝甘露"),
    FoodItem("钵仔糕"),
    FoodItem("猪脚姜"),
    FoodItem("艇仔粥"),
    FoodItem("及第粥"),
    FoodItem("陈村粉"),
    FoodItem("均安蒸猪"),
    FoodItem("均安鱼饼"),
    FoodItem("大良炒牛奶"),
    FoodItem("大良蹦砂"),
    FoodItem("伦教糕"),
    FoodItem("龙江猪脚饭"),
    FoodItem("潮汕牛肉丸"),
    FoodItem("蚝烙"),
    FoodItem("粿条汤"),
    FoodItem("砂锅粥"),
    FoodItem("卤鹅"),
    FoodItem("猪肠粉"),
    FoodItem("牛肉火锅"),
    FoodItem("粿汁"),
    FoodItem("咸水粿"),
    FoodItem("无米粿"),
)

// 各校区食物池。
// TODO: 待替换为各校区真实食堂/窗口数据——提供列表后分别填入以下两个集合即可。
private val developmentFoodItems: List<FoodItem> = commonFoodItems

private val jinshitanFoodItems: List<FoodItem> = commonFoodItems

/** 按校区返回对应食物池 */
fun foodItemsFor(campus: Campus): List<FoodItem> = when (campus) {
    Campus.Development -> developmentFoodItems
    Campus.Jinshitan -> jinshitanFoodItems
}
